In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from config import gkey

In [4]:
beer_df=pd.read_csv("Resources/clean_beer_data_try2.csv")
beer_df.head()

,index,beer_name,brewery_name,beer_style,country,beer_abv,review_overall,review_aroma,review_appearance,review_palate,review_taste,beer_review_count,brewery_review,brewery_review_count,lat,lng,beer_id,brewery_id
0,0,(512) IPA,(512) Brewing Company,American IPA,United States,7.0,4.259259,4.129630,4.009259,4.101852,4.185185,54,4.22,135,30.222972,-97.770152,43535,17863
1,1,(512) Pecan Porter,(512) Brewing Company,American Porter,United States,6.8,4.185185,4.067901,4.166667,3.981481,4.166667,81,4.22,135,30.222972,-97.770152,45617,17863
2,2,Hell Or High Watermelon Wheat Beer,21st Amendment Brewery,Fruit / Vegetable Beer,United States,4.9,3.388771,3.116525,3.237288,3.325212,3.237288,472,3.71,2767,37.782525,-122.392460,4202,735
3,3,21st Amendment IPA,21st Amendment Brewery,American IPA,United States,7.0,3.890769,3.801538,3.977692,3.771538,3.767692,650,3.71,2767,37.782525,-122.392460,20781,735
4,4,Bitter American,21st Amendment Brewery,American Pale Ale (APA),United States,4.4,4.118421,3.921053,3.927632,3.769737,3.898026,152,3.71,2767,37.782525,-122.392460,34791,735

In [9]:
#Strip only leaving the breweries from the United States, their rating and the latitude and longitude
USA_df=beer_df.loc[(beer_df["country"]=="United States"),["brewery_name","brewery_review","lat","lng"]]
USA_df.drop_duplicates(keep="first",inplace=True)
USA_df

                        brewery_name  brewery_review        lat         lng
0              (512) Brewing Company            4.22  30.222972  -97.770152
2             21st Amendment Brewery            3.71  37.782525 -122.392460
17                 Abita Brewing Co.            3.58  30.482108  -90.055018
37                 Alameda Brewhouse            4.01  45.548459 -122.613639
38               Alaskan Brewing Co.            3.85  58.357573 -134.486348
...                              ...             ...        ...         ...
4259           Woodstock Inn Brewery            3.53  44.032430  -71.686912
4265               Yards Brewing Co.            3.78  39.960971  -75.146909
4274           Yazoo Brewing Company            3.85  36.275565  -86.686512
4278  Yellowstone Valley Brewing Co.            3.61  45.780615 -108.508556
4279              Yuengling Brewery             3.42  40.683249  -76.197799

[390 rows x 4 columns]

In [13]:
#configure gmaps
gmaps.configure(api_key=gkey)
locations=USA_df[["lat","lng"]]
weight=USA_df["brewery_review"]

#create heat layer centered on Kansas
heat_layer=gmaps.heatmap_layer(locations,weights=weight,dissipating=False,
                              max_intensity=50,point_radius=3)
fig=gmaps.figure(center=(39.8097343,-98.5556199),zoom_level=4)
#add layer
fig.add_layer(heat_layer)
#display figure
fig

Figure(layout=FigureLayout(height='420px'))