In [1]:
import pandas as pd
import requests
import json
from config import gkey
from pprint import pprint
import numpy as np

In [3]:
#Grab all the beer review data from file
beer_review_data=pd.read_csv('Resources/beer_reviews.csv', encoding="utf-8")
beer_review_data

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,10325,Vecchio Birraio,1234817823,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,10325,Vecchio Birraio,1235915097,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,10325,Vecchio Birraio,1235916604,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,10325,Vecchio Birraio,1234725145,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,1075,Caldera Brewing Company,1293735206,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1586609,14359,The Defiant Brewing Company,1162684892,5.0,4.0,3.5,maddogruss,Pumpkin Ale,4.0,4.0,The Horseman's Ale,5.2,33061
1586610,14359,The Defiant Brewing Company,1161048566,4.0,5.0,2.5,yelterdow,Pumpkin Ale,2.0,4.0,The Horseman's Ale,5.2,33061
1586611,14359,The Defiant Brewing Company,1160702513,4.5,3.5,3.0,TongoRad,Pumpkin Ale,3.5,4.0,The Horseman's Ale,5.2,33061
1586612,14359,The Defiant Brewing Company,1160023044,4.0,4.5,4.5,dherling,Pumpkin Ale,4.5,4.5,The Horseman's Ale,5.2,33061
1586613,14359,The Defiant Brewing Company,1160005319,5.0,4.5,4.5,cbl2,Pumpkin Ale,4.5,4.5,The Horseman's Ale,5.2,33061

In [31]:
#Find the average value for the reviews by the beer name
beer_group=beer_review_data.groupby(["beer_beerid","beer_name","brewery_name","beer_style","brewery_id"])
beer_df=pd.DataFrame(beer_group["review_overall","review_aroma","review_appearance","review_taste","review_palate","beer_abv"].mean())

beer_df=beer_df.reset_index()

beer_df

C:\Users\jchaf\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  This is separate from the ipykernel package so we can avoid doing imports until

,beer_beerid,beer_name,brewery_name,beer_style,brewery_id,review_overall,review_aroma,review_appearance,review_taste,review_palate,beer_abv
0,3,Cactus Queen IPA,Yellow Rose Brewing Company,American IPA,2,4.166667,4.000000,3.833333,4.166667,4.166667,NaN
1,4,Wildcatter's Crude Stout,Yellow Rose Brewing Company,American Stout,2,3.700000,3.800000,3.950000,3.450000,3.700000,NaN
2,5,Amber,Abita Brewing Co.,Vienna Lager,3,3.549528,3.205189,3.485849,3.340802,3.318396,4.5
3,6,Turbodog,Abita Brewing Co.,English Brown Ale,3,3.706956,3.515964,3.836374,3.645382,3.513113,5.6
4,7,Purple Haze,Abita Brewing Co.,Fruit / Vegetable Beer,3,3.266313,3.179059,3.251138,3.101669,3.106980,4.2
...,...,...,...,...,...,...,...,...,...,...,...
66039,77313,Aass Gourmet Pale Ale,Aass Brewery,American Blonde Ale,185,3.000000,3.000000,4.000000,3.000000,3.000000,4.7
66040,77314,Betty Brown Norwegian Brwon Ale,Lervig Aktiebryggeri AS,American Brown Ale,18604,3.500000,3.500000,4.000000,4.000000,3.000000,4.7
66041,77315,Icelandic White Beer,EinstÃ¶k Ã–lgerÃ°,Witbier,27839,3.500000,4.500000,3.000000,3.500000,3.000000,5.2
66042,77316,Crank Yanker IPA,Eddyline Restaurant & Brewery,American IPA,20330,3.500000,3.500000,3.500000,3.500000,3.500000,7.8
66043,77317,Belgo Sutra,Magic Hat Brewing Company,Quadrupel (Quad),96,3.500000,3.500000,4.000000,4.000000,3.500000,NaN

In [32]:
#Get a count of the number of reviews for each beer
review_count=beer_review_data.groupby(["beer_beerid"]).count()
review_count=review_count[["review_overall"]]
review_count.head()

             review_overall
beer_beerid
3                         3
4                        10
5                       424
6                       877
7                       659

In [33]:
#Merge average review dataframe and review count dataframe
beer_merged_data = pd.merge(beer_df, review_count, on='beer_beerid', how='outer')
beer_merged_data = beer_merged_data.rename(columns={'review_overall_x': 'review_overall', 'review_overall_y': 'review_count'})


beer_merged_data.head()

,beer_beerid,beer_name,brewery_name,beer_style,brewery_id,review_overall,review_aroma,review_appearance,review_taste,review_palate,beer_abv,review_count
0,3,Cactus Queen IPA,Yellow Rose Brewing Company,American IPA,2.0,4.166667,4.000000,3.833333,4.166667,4.166667,NaN,3
1,4,Wildcatter's Crude Stout,Yellow Rose Brewing Company,American Stout,2.0,3.700000,3.800000,3.950000,3.450000,3.700000,NaN,10
2,5,Amber,Abita Brewing Co.,Vienna Lager,3.0,3.549528,3.205189,3.485849,3.340802,3.318396,4.5,424
3,6,Turbodog,Abita Brewing Co.,English Brown Ale,3.0,3.706956,3.515964,3.836374,3.645382,3.513113,5.6,877
4,7,Purple Haze,Abita Brewing Co.,Fruit / Vegetable Beer,3.0,3.266313,3.179059,3.251138,3.101669,3.106980,4.2,659

In [34]:
#filter out those with less than 50 reviews
beer_50review=beer_merged_data.loc[(beer_merged_data["review_count"]>50),:]
beer_50review

,beer_beerid,beer_name,brewery_name,beer_style,brewery_id,review_overall,review_aroma,review_appearance,review_taste,review_palate,beer_abv,review_count
2,5,Amber,Abita Brewing Co.,Vienna Lager,3.0,3.549528,3.205189,3.485849,3.340802,3.318396,4.5,424
3,6,Turbodog,Abita Brewing Co.,English Brown Ale,3.0,3.706956,3.515964,3.836374,3.645382,3.513113,5.6,877
4,7,Purple Haze,Abita Brewing Co.,Fruit / Vegetable Beer,3.0,3.266313,3.179059,3.251138,3.101669,3.106980,4.2,659
5,8,Wheat,Abita Brewing Co.,American Adjunct Lager,3.0,3.647059,3.080882,3.294118,3.235294,3.301471,4.2,68
6,9,Golden,Abita Brewing Co.,American Pale Lager,3.0,3.400862,2.853448,3.051724,3.043103,3.103448,4.2,116
...,...,...,...,...,...,...,...,...,...,...,...,...
63995,75086,Stone 11.11.11 Vertical Epic Ale,Stone Brewing Co.,Belgian Strong Pale Ale,147.0,3.655109,3.750000,3.894161,3.693431,3.753650,9.4,274
64088,75188,Baller Stout,Three Floyds Brewing Co. & Brewpub,Russian Imperial Stout,26.0,4.086538,4.067308,4.230769,4.067308,4.067308,13.8,52
64129,75230,Trader Joe's 2011 Vintage Ale,Trader Joe's Brewing Company,Belgian Strong Dark Ale,10707.0,3.745902,3.696721,3.877049,3.680328,3.557377,9.0,61
64985,76144,He'Brew Jewbelation Fifteen,Shmaltz Brewing Company,American Strong Ale,262.0,4.129630,4.083333,4.009259,4.185185,4.129630,15.0,54
65352,76525,The Alchemist / Ninkasi / Stone - More Brown T...,Stone Brewing Co.,American IPA,147.0,4.070175,4.254386,3.903509,4.105263,4.017544,7.4,57

In [35]:
#Write file with all beer with above 50 reviews
beer_50review.to_csv('Output/beer_review_avg_worldwide_try2.csv')

In [14]:
#Create new data frame for breweries
brewery_df= beer_50review.groupby(["brewery_name", "brewery_id"])
#find brewery rating based on average beer review
average_rating = round(brewery_df['review_overall'].mean(), 2)
#get the total count of reviews made on beers from each brewery
review_count=brewery_df["review_count"].sum()

brewery_df = pd.DataFrame(average_rating)
brewery_df["review_count"]=review_count
brewery_df = brewery_df.reset_index()
brewery_df = brewery_df.rename(columns={'brewery_name': 'Brewery'})

brewery_df

#brew_test=brewery_df.head(10)

                             Brewery  brewery_id  review_overall  review_count
0              (512) Brewing Company     17863.0            4.22           135
1             21st Amendment Brewery       735.0            3.71          2767
2                 AS Tartu Ã•lletehas      1349.0            2.76            58
3               Abbaye de Leffe S.A.       470.0            3.74          1777
4                  Abita Brewing Co.         3.0            3.58          4922
..                               ...         ...             ...           ...
873  Zywiec Breweries PLC (Heineken)       623.0            3.48           700
874           the Nils Oscar Company       894.0            3.78           298
875                 ÂŽÅ½ateckÃ½ Pivovar      4106.0            3.74           125
876           Ã€ lâ€™abri de la TempÃªte     11256.0            3.89            55
877                      Ã˜lfabrikken     11063.0            3.99           398

[878 rows x 4 columns]

In [15]:
#create new columns to save stuff from api
brewery_df["lat"]=''
brewery_df["lng"]=''
brewery_df["address"]=''

<h1>Time for some google api shenanigans</h1>

In [16]:
#setup fields that I want from google and basic
field="geometry/location,formatted_address"
base_url = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json?"

#set up for loop to go through every row of my brewery dataframe
for index, row in brewery_df.iterrows():
    params = {
        "input": row['Brewery'],
        "key": gkey,
        "inputtype":"textquery",
        "fields": field
    }
    
    top_response = requests.get(base_url, params=params)
    result = top_response.json()
    try:
        #attempt to save data from google
        brewery_df.loc[index, 'lat'] = result['candidates'][0]['geometry']['location']['lat']
        brewery_df.loc[index, 'lng'] = result['candidates'][0]['geometry']['location']['lng']
        brewery_df.loc[index, 'address'] = result['candidates'][0]['formatted_address']
    
    except (KeyError, IndexError):
        #output lack of results from query
        print(f"No Google result for {row['Brewery']}......Skipping.....")

No Google result for Adnams plc, Sole Bay Brewery......Skipping.....
No Google result for Amstel Brouwerij B. V.......Skipping.....
No Google result for Anadolu Efes Brewery......Skipping.....
No Google result for Asahi Breweries Ltd......Skipping.....
No Google result for Ass Kisser Ales......Skipping.....
No Google result for Associated Breweries & Distilleries Ltd.......Skipping.....
No Google result for BFM Brasserie Des Franches-Montagnes......Skipping.....
No Google result for BJ's Chicago Pizza & Brewery Inc.......Skipping.....
No Google result for Baird Brewing Company / Fishmarket Taproom......Skipping.....
No Google result for Baltika Breweries......Skipping.....
No Google result for Bard's Tale Beer Company, LLC......Skipping.....
No Google result for Bass Brewers Limited......Skipping.....
No Google result for Bavaria Brouwerij N.V.......Skipping.....
No Google result for Bayhawk Ales......Skipping.....
No Google result for Beamish & Crawford Plc.......Skipping.....
No Google result for Beau's All Natural Brewing Company......Skipping.....
No Google result for Beijing Yanjing Beer Group Corporation......Skipping.....
No Google result for Birra Menabrea SpA......Skipping.....
No Google result for Birra Moretti (Heineken)......Skipping.....
No Google result for Bitburger Brauerei......Skipping.....
No Google result for BiÃ¨res de Chimay S.A.......Skipping.....
No Google result for Black Sheep Brewery PLC......Skipping.....
No Google result for Black Toad Brewing Co.......Skipping.....
No Google result for Blitz-Weinhard Brewing Co.......Skipping.....
No Google result for Boak Beverage......Skipping.....
No Google result for Brasserie Almaza S.A.L.......Skipping.....
No Google result for Brasserie Ellezelloise......Skipping.....
No Google result for Brasserie Grain d' Orge (Brasserie Jeanne d'Arc SA)......Skipping.....
No Google result for Brasserie La Binchoise (Malterie des Remparts)......Skipping.....
No Google result for Brasserie Pietra......Skipping.....
No Google result for Brasserie Theillier......Skipping.....
No Google result for Brasserie de Silly S.A.......Skipping.....
No Google result for Brauerei Beck & Co.......Skipping.....
No Google result for Brauerei GebrÃ¼der Maisel GmbH & Co.......Skipping.....
No Google result for Brauerei Grieskirchen AG......Skipping.....
No Google result for Brauerei GÃ¶ss (Brau Union)......Skipping.....
No Google result for Brauerei Heller-Trum / Schlenkerla......Skipping.....
No Google result for Brauerei Michael Plank......Skipping.....
No Google result for Brauerei Tucher Brau......Skipping.....
No Google result for Brewery Budweiser Budvar / B.B.N.P.......Skipping.....
No Google result for Brick Brewing Co. / Red Baron Lounge......Skipping.....
No Google result for Brouwerij De Bie / D'Hellekappelle......Skipping.....
No Google result for Brouwerij De Smedt / Brouwerij Affligem......Skipping.....
No Google result for Brouwerij Louwaege......Skipping.....
No Google result for Brouwerij Riva S.A.......Skipping.....
No Google result for Brouwerij Slaapmutske......Skipping.....
No Google result for Brouwerij Smisje......Skipping.....
No Google result for Brouwerij St. Bernardus NV......Skipping.....
No Google result for Brouwerij Timmermans-John Martin N.V.......Skipping.....
No Google result for Brouwerij Van Honsebrouck N.V.......Skipping.....
No Google result for Browar Okocim S.A. (Carlsberg)......Skipping.....
No Google result for Bryggeriet DjÃ¦vlebryg ApS......Skipping.....
No Google result for Buckbean Brewing Company......Skipping.....
No Google result for Bud&#283;jovickÃ½ M&#283;Âš&#357;anskÃ½ Pivovar......Skipping.....
No Google result for CB's Brewing Company......Skipping.....
No Google result for Carlsberg-Tetley Brewing Ltd......Skipping.....
No Google result for Carlton & United Breweries, Ltd.......Skipping.....
No Google result for Casco Bay Brewing Co.......Skipping.....
No Google result for Central City Brewing......Skipping.....
No Google result for CervecerÃ­a de MateVeza......Skipping.....
No Google result for CervecerÃ­a y MalterÃ­a Quilmes / Grupo Bemberg......Skipping.....
No Google result for Cervejaria Kaiser......Skipping.....
No Google result for Cervejaria Sudbrack Ltda......Skipping.....
No Google result for Cervejaria Sul Brasileira......Skipping.....
No Google result for Christian Moerlein Brewing Company......Skipping.....
No Google result for Cisco Brewers Inc.......Skipping.....
No Google result for Clay Pipe Brewing Company......Skipping.....
No Google result for Clown Shoes......Skipping.....
No Google result for Coastal Extreme Brewing Co.......Skipping.....
No Google result for Commonwealth Brewery Ltd.......Skipping.....
No Google result for Companhia Cervejaria Brahma......Skipping.....
No Google result for Compania Cervecera Del Sur Del Peru S.A. (Cervesur)......Skipping.....
No Google result for Cosmos Brewery (Thai Beverage Plc.)......Skipping.....
No Google result for CucapÃ¡ Brewing Company......Skipping.....
No Google result for Damm S. A.......Skipping.....
No Google result for Daniel Thwaites Brewery PLC......Skipping.....
No Google result for De Cam Geuzestekerij......Skipping.....
No Google result for De Leyerth Brouwerijen (Urthel)......Skipping.....
No Google result for Denison's Brewing Company......Skipping.....
No Google result for Desnoes & Geddes Limited......Skipping.....
No Google result for Dixie Brewing Co.......Skipping.....
No Google result for Drake's Brewing Co.......Skipping.....
No Google result for Elbrewery Co. Ltd. Sp. z o.o.......Skipping.....
No Google result for Element Brewing Company......Skipping.....
No Google result for Elysian Brewing Company......Skipping.....
No Google result for Endurance Brewing Company......Skipping.....
No Google result for Especialidades Cerveceras S.A. de C.V.......Skipping.....
No Google result for F & M Schaefer Brewing Co.......Skipping.....
No Google result for Fiddler's Green Brewing Company......Skipping.....
No Google result for Fire Station 5 Brewing Company......Skipping.....
No Google result for Fish Brewing Company / Fishbowl Brewpub......Skipping.....
No Google result for Foster's Group Limited......Skipping.....
No Google result for Freeminer Brewery Ltd.......Skipping.....
No Google result for Fuller Smith & Turner PLC......Skipping.....
No Google result for Gebr. SÃ¼nner GmbH & Co. KG......Skipping.....
No Google result for General Lafayette Inn & Brewery......Skipping.....
No Google result for Genesee Brewing Co. / Dundee Brewing Co.......Skipping.....
No Google result for George Gale & Company Ltd......Skipping.....
No Google result for Gordash Brewing Company......Skipping.....
No Google result for Green Valley Brewing Company (Crooked Creek)......Skipping.....
No Google result for Greene King / Morland Brewery......Skipping.....
No Google result for Gritty McDuff's Brewing Company......Skipping.....
No Google result for Grupo Cervezas Alhambra, SL......Skipping.....
No Google result for Gubernija Brewery......Skipping.....
No Google result for Guinness Ltd.......Skipping.....
No Google result for Hacker-Pschorr BrÃ¤u GmbH......Skipping.....
No Google result for Hamm's Brewing Co.......Skipping.....
No Google result for Hanseatische GetrÃ¤nke-Industrie (HGI) Holsten-Brauerei AG......Skipping.....
No Google result for Harbin Brewery Group......Skipping.....
No Google result for Heavyweight Brewing Co.......Skipping.....
No Google result for High & Mighty Beer Co.......Skipping.....
No Google result for Hite Brewery Company LTD......Skipping.....
No Google result for HofbrÃ¤u Kaltenhausen (Brau Union)......Skipping.....
No Google result for Hudepohl-Schoenling Brewing Co.......Skipping.....
No Google result for J. Boag & Son Brewing......Skipping.....
No Google result for JOS. Schlitz Brewing Co. (Pabst)......Skipping.....
No Google result for James Page Brewing Company......Skipping.....
No Google result for KEO Limited......Skipping.....
No Google result for Karlova&#267;ka Pivovara......Skipping.....
No Google result for Kirin Brewery Company, Limited......Skipping.....
No Google result for Kirkland Signature / Costco Wholesale Corporation......Skipping.....
No Google result for Kiuchi Brewery......Skipping.....

No Google result for KrÃ¡lovskÃ½ Pivovar KruÅ¡ovice a.s.......Skipping.....
No Google result for Labatt Brewing Company Ltd.......Skipping.....
No Google result for Lech Browary Wielkopolski (SABMiller)......Skipping.....
No Google result for LÃ¶wenbrÃ¤u AG......Skipping.....
No Google result for M&#283;Âš&#357;anskÃ½ Pivovar HavlÃ­&#269;k&#367;v Brod, A.S.......Skipping.....
No Google result for Malt Shovel Brewery......Skipping.....
No Google result for Margaritaville Brewing Co.......Skipping.....
No Google result for Marston, Thompson & Evershed, Plc.......Skipping.....
No Google result for Meantime Brewing Company Limited......Skipping.....
No Google result for Melanie Brewing Company......Skipping.....
No Google result for Mikkeller ApS......Skipping.....
No Google result for Molson Coors Canada......Skipping.....
No Google result for Monteith's Brewing Co.......Skipping.....
No Google result for Mythos Breweries S.A.......Skipping.....
No Google result for Nectar Ales......Skipping.....
No Google result for Nethergate Brewery Co. Ltd.......Skipping.....
No Google result for New Zealand Breweries Limited......Skipping.....
No Google result for O'Hanlon's Brewing Co. Ltd.......Skipping.....
No Google result for Obolon Brewery......Skipping.....
No Google result for Ochakovo......Skipping.....
No Google result for Odonata Beer Company......Skipping.....
No Google result for Olde Towne Brewing Co.......Skipping.....
No Google result for Orange Blossom Pilsner LLC......Skipping.....
No Google result for Oranjeboom Bierbrouwerij B. V.......Skipping.....
No Google result for Orion Beer Co., Ltd.......Skipping.....
No Google result for Otter Creek Brewing / Wolaver's......Skipping.....
No Google result for Park & Bellheimer AG......Skipping.....
No Google result for Peak Organic Brewing Company......Skipping.....
No Google result for Pennichuck Brewing Company, Inc.......Skipping.....
No Google result for Picobrouwerij Alvinne / Den Bierzolder......Skipping.....
No Google result for Pivovar Herold B&#345;eznice A.s.......Skipping.....
No Google result for Pivovar Starbrno, A.S.......Skipping.....
No Google result for Pivovar Zlaty Bazant a.s.......Skipping.....
No Google result for Pretty Things Beer & Ale Project......Skipping.....
No Google result for Privatbrauerei Franz Joseph Sailer......Skipping.....
No Google result for Privatbrauerei Schwelm......Skipping.....
No Google result for Private Stock Brewing Co.......Skipping.....
No Google result for Professor Fritz Briem......Skipping.....
No Google result for Pyramid Breweries, Inc.......Skipping.....
No Google result for ReaperAle......Skipping.....
No Google result for Rex Beverage Holdings......Skipping.....
No Google result for Royal Unibrew A/S......Skipping.....
No Google result for Saint Ides Brewing Company......Skipping.....
No Google result for Sapporo Breweries Ltd.......Skipping.....
No Google result for Simonds Farsons Cisk Plc.......Skipping.....
No Google result for Slavutych Brewery......Skipping.....
No Google result for Smithwick's Brewery / Irish Ale Breweries Ltd......Skipping.....
No Google result for South African Breweries plc......Skipping.....
No Google result for Spanish Peaks Brewing Co.......Skipping.....
No Google result for St. Pauli Brauerei C.L. Wilh. Brandt Gmbh & Co.......Skipping.....
No Google result for Steel Brewing Company......Skipping.....
No Google result for Steinhaus Brewing Co.......Skipping.....
No Google result for Stillwater Artisanal Ales......Skipping.....
No Google result for Stone Coast Brewing Co.......Skipping.....
No Google result for Strangford Lough Brewing Company Ltd......Skipping.....
No Google result for The Brew Kettle Taproom & Smokehouse / Production Works......Skipping.....
No Google result for The Caledonian Brewery Company Limited......Skipping.....
No Google result for The Lucky Drink Co. Pty Limited......Skipping.....
No Google result for The Porterhouse Brewing Company......Skipping.....
No Google result for Thomas Caffrey Brewing Co.......Skipping.....
No Google result for Timothy Taylor & Co. Limited......Skipping.....
No Google result for Tooheys Brewing......Skipping.....
No Google result for Trader Joe's Brewing Company......Skipping.....
No Google result for Tsingtao Brewery Co., Ltd.......Skipping.....
No Google result for Tuborgs Bryggerier A/S......Skipping.....
No Google result for Tuppers' Hop Pocket Brewing Company......Skipping.....
No Google result for Tyskie Browary Ksi&#261;&#380;&#281;ce (SABMiller)......Skipping.....
No Google result for UAB Å vyturys......Skipping.....
No Google result for UNICER UniÃ£o Cervejeira S.A.......Skipping.....
No Google result for Uehara Shuzou Co. Ltd. / Echigo Beer Pub......Skipping.....
No Google result for Union De Cervecerias Peruanas Backus y Johnston......Skipping.....
No Google result for Union Export Brewery......Skipping.....
No Google result for United Breweries - UB Group......Skipping.....
No Google result for Upper Canada Brewing Company......Skipping.....
No Google result for Utenos Alus......Skipping.....
No Google result for VBL Tien Giang Limited (Fosters)......Skipping.....
No Google result for Vanberg & DeWulf......Skipping.....
No Google result for W.H. Brakspear & Sons plc......Skipping.....
No Google result for Weisses BrÃ¤uhaus G. Schneider & Sohn GmbH......Skipping.....
No Google result for Wells & Young's Ltd......Skipping.....
No Google result for WernesgrÃ¼ner Brauerei AG......Skipping.....
No Google result for Wild Goose Brewery, LLC......Skipping.....
No Google result for Wolnzacher BÃ¼rgerbraÃ¼ AG......Skipping.....
No Google result for World Brews......Skipping.....
No Google result for Wychwood Brewery Company Ltd......Skipping.....
No Google result for Yakima Brewing Co. / Bert Grant's Ales......Skipping.....
No Google result for Young & Co Brewery PLC......Skipping.....
No Google result for Z Street Brewing Company......Skipping.....
No Google result for Zak&#322;ady Piwowarskie w Le&#380;ajsku S.A.......Skipping.....
No Google result for Zywiec Breweries PLC (Heineken)......Skipping.....
No Google result for ÂŽÅ½ateckÃ½ Pivovar......Skipping.....
No Google result for Ã˜lfabrikken......Skipping.....

In [18]:
brewery_df

,Brewery,brewery_id,review_overall,review_count,lat,lng,address
0,(512) Brewing Company,17863.0,4.22,135,30.223,-97.7702,"407 Radam Ln, Austin, TX 78745, United States"
1,21st Amendment Brewery,735.0,3.71,2767,37.7825,-122.392,"563 2nd St, San Francisco, CA 94107, United St..."
2,AS Tartu Ã•lletehas,1349.0,2.76,58,58.3859,26.7073,"51007 Tartu, Estonia"
3,Abbaye de Leffe S.A.,470.0,3.74,1777,50.2689,4.9075,"Place de l'Abbaye 1, 5500 Dinant, Belgium"
4,Abita Brewing Co.,3.0,3.58,4922,30.4821,-90.055,"21084 LA-36, Covington, LA 70433, United States"
...,...,...,...,...,...,...,...
873,Zywiec Breweries PLC (Heineken),623.0,3.48,700,,,
874,the Nils Oscar Company,894.0,3.78,298,58.7478,17.0064,"FruÃ¤ngsgatan 2, 611 31 NykÃ¶ping, Sweden"
875,ÂŽÅ½ateckÃ½ Pivovar,4106.0,3.74,125,,,
876,Ã€ lâ€™abri de la TempÃªte,11256.0,3.89,55,47.351,-61.9473,"286 Chemin Coulombe, L'Ã‰tang-du-Nord, QC G4T 3..."
877,Ã˜lfabrikken,11063.0,3.99,398,,,

In [19]:
#fill empty locations with Nan and then drop
brewery_df=brewery_df.replace(r'^\s*$', np.NaN, regex=True)
brewery_df.dropna(inplace = True)
brewery_df

,Brewery,brewery_id,review_overall,review_count,lat,lng,address
0,(512) Brewing Company,17863.0,4.22,135,30.222972,-97.770152,"407 Radam Ln, Austin, TX 78745, United States"
1,21st Amendment Brewery,735.0,3.71,2767,37.782525,-122.392460,"563 2nd St, San Francisco, CA 94107, United St..."
2,AS Tartu Ã•lletehas,1349.0,2.76,58,58.385906,26.707300,"51007 Tartu, Estonia"
3,Abbaye de Leffe S.A.,470.0,3.74,1777,50.268889,4.907500,"Place de l'Abbaye 1, 5500 Dinant, Belgium"
4,Abita Brewing Co.,3.0,3.58,4922,30.482108,-90.055018,"21084 LA-36, Covington, LA 70433, United States"
...,...,...,...,...,...,...,...
867,Yellowstone Valley Brewing Co.,1125.0,3.61,64,45.780615,-108.508556,"3008 1st Ave N, Billings, MT 59101, United States"
869,Yuengling Brewery,23980.0,3.42,3342,40.683249,-76.197799,"420 Mahantongo St, Pottsville, PA 17901, Unite..."
870,Yukon Brewing Company,4701.0,3.87,54,60.738056,-135.078889,"102 Copper Rd, Whitehorse, YT Y1A 2Z6, Canada"
874,the Nils Oscar Company,894.0,3.78,298,58.747829,17.006378,"FruÃ¤ngsgatan 2, 611 31 NykÃ¶ping, Sweden"
876,Ã€ lâ€™abri de la TempÃªte,11256.0,3.89,55,47.351028,-61.947300,"286 Chemin Coulombe, L'Ã‰tang-du-Nord, QC G4T 3..."

In [20]:
#create new coulmns to save a split of the address column
brewery_df["street_address"]=""
brewery_df["city"]=""
brewery_df["postal_code"]=''
brewery_df["country"]=''
brewery_df.head()

,Brewery,brewery_id,review_overall,review_count,lat,lng,address,street_address,city,postal_code,country
0,(512) Brewing Company,17863.0,4.22,135,30.222972,-97.770152,"407 Radam Ln, Austin, TX 78745, United States",,,,
1,21st Amendment Brewery,735.0,3.71,2767,37.782525,-122.392460,"563 2nd St, San Francisco, CA 94107, United St...",,,,
2,AS Tartu Ã•lletehas,1349.0,2.76,58,58.385906,26.707300,"51007 Tartu, Estonia",,,,
3,Abbaye de Leffe S.A.,470.0,3.74,1777,50.268889,4.907500,"Place de l'Abbaye 1, 5500 Dinant, Belgium",,,,
4,Abita Brewing Co.,3.0,3.58,4922,30.482108,-90.055018,"21084 LA-36, Covington, LA 70433, United States",,,,

In [21]:
for index, row in brewery_df.iterrows():
    #split and reverse so country is first
    addresssplit=row["address"].split(", ")
    addresssplit.reverse()
    try:
        #attempt to save values to each location
        brewery_df.loc[index, 'country'] = addresssplit[0]
        brewery_df.loc[index, 'postal_code'] = addresssplit[1]
        brewery_df.loc[index, 'city'] = addresssplit[2]
        brewery_df.loc[index, 'street_address']=addresssplit[3]
    except(IndexError):
        #output errors
        print(f"funky address for {row['Brewery']}")
brewery_df.head(10)

funky address for AS Tartu Ã•lletehas
funky address for Abbaye de Leffe S.A.
funky address for Aktien-Brauerei Kaufbeuren AG
funky address for AllgÃ¤uer Brauhaus AG
funky address for Amager Bryghus
funky address for Asia Pacific Breweries Ltd.
funky address for Augustiner-BrÃ¤u Wagner KG
funky address for BOSS Browar Witnica S.A.
funky address for Badische Staatsbrauerei Rothaus AG
funky address for Banks (Barbados) Breweries Limited
funky address for Barrel House Brewing Company
funky address for Bayerische Staatsbrauerei Weihenstephan
funky address for Berliner Kindl Brauerei
funky address for Bierbrouwerij De Koningshoeven B.V.
funky address for Bierbrouwerij Grand-CafÃ©  Emelisse
funky address for Bierbrouwerij Sint Christoffel B.V
funky address for Binding-Brauerei AG
funky address for Brasserie Artisanale De RullÃ©s SPRL
funky address for Brasserie Belle-Vue
funky address for Brasserie Cantillon
funky address for Brasserie Caracole
funky address for Brasserie Castelain
funky address for Brasserie De Brunehaut
funky address for Brasserie De Saint-Sylvestre
funky address for Brasserie Des GÃ©ants
funky address for Brasserie Du Bocq
funky address for Brasserie Dubuisson FrÃ¨res sprl
funky address for Brasserie Dupont sprl
funky address for Brasserie Duyck
funky address for Brasserie FantÃ´me
funky address for Brasserie Fischer / Fischer Biere d' Alsace
funky address for Brasserie La Choulette
funky address for Brasserie LefÃ¨bvre SA
funky address for Brasserie Piedboeuf
funky address for Brasserie St. Feuillien
funky address for Brasserie Thiriez
funky address for Brasserie d'Achouffe
funky address for Brasserie d'Orval S.A.
funky address for Brasserie de Blaugies
funky address for Brasserie de Rochefort
funky address for Brasserie de Saverne
funky address for Brasserie de Tahiti S.A.
funky address for Brasserie de l'Abbaye des Rocs s.a.
funky address for Brasserie de l'Abbaye du Val-Dieu
funky address for Brasserie de la Senne
funky address for Brasserie Ã  Vapeur
funky address for Brasseries Du Maroc
funky address for Brasseries Kronenbourg
funky address for Brau Union Ã–sterreich AG
funky address for Brauerei C. & A. Veltins GmbH & Co.
funky address for Brauerei Diebels GmbH & Co KG
funky address for Brauerei FrÃ¼h Am Dom
funky address for Brauerei Heinrich Reissdorf
funky address for Brauerei Hofstetten Krammer GmbH & Co. KG
funky address for Brauerei Pinkus Mueller
funky address for Brauerei Schloss Eggenberg
funky address for Brauerei Spezial
funky address for Brouwerij 't Gaverhopke
funky address for Brouwerij 't IJ
funky address for Brouwerij Alken-Maes
funky address for Brouwerij Bavik
funky address for Brouwerij Bockor N.V.
funky address for Brouwerij Boon
funky address for Brouwerij Bosteels
funky address for Brouwerij Corsendonk
funky address for Brouwerij De Block bvba
funky address for Brouwerij De Dolle Brouwers
funky address for Brouwerij De Koninck NV
funky address for Brouwerij De Landtsheer NV
funky address for Brouwerij De Molen
funky address for Brouwerij De Musketiers
funky address for Brouwerij De Ranke
funky address for Brouwerij De Troch
funky address for Brouwerij Drie Fonteinen
funky address for Brouwerij Duvel Moortgat NV
funky address for Brouwerij Girardin
funky address for Brouwerij Het Anker
funky address for Brouwerij Huyghe
funky address for Brouwerij Kerkom
funky address for Brouwerij Liefmans
funky address for Brouwerij Lindemans
funky address for Brouwerij Mort Subite
funky address for Brouwerij Oud Beersel
funky address for Brouwerij Palm NV
funky address for Brouwerij Rodenbach N.V.
funky address for Brouwerij Roman N.V.
funky address for Brouwerij Slaghmuylder
funky address for Brouwerij Sterkens N.V.
funky address for Brouwerij Straffe Hendrik / Huisbrouwerij De Halve Maan
funky address for Brouwerij Strubbe
funky address for Brouwerij Van Eecke N.V.
funky address for Brouwerij Van Steenberge N.V.
funky address for Brouwerij Van den Bossche
funky address for Brouwerij Verhaeghe
funky address for Brouwerij Westmalle
funky address for Brouwerij Westvleteren (Sint-Sixtusabdij van Westvleteren)
funky address for Brouwerij der St. Benedictusabdij de Achelse
funky address for Brouwerij van Hoegaarden
funky address for Browary Warka Sp. z o.o.
funky address for Browerij Nacional Balashi
funky address for Burton Bridge Brewery
funky address for Carib Brewery Limited
funky address for Carlsberg Danmark A/S
funky address for Carlsberg Sverige AB
funky address for Castle Eden & Camerons Brewing Company Ltd
funky address for Cerveceria Costa Rica
funky address for Cerveceria Nacional Dominicana
funky address for CervecerÃ­a Centro Americana, S.A.
funky address for Ceylon / Lion Brewery Limited
funky address for Coniston Brewing Co. Ltd
funky address for Coopers Brewery Limited
funky address for Cropton Brewery
funky address for Daleside Brewery
funky address for De Proefbrouwerij (bvba Andelot)
funky address for De Struise Brouwers
funky address for Der HirschBrau/Privatbrauerei HÃ¶ss
funky address for Dinkelacker-Schwabenbraeu AG
funky address for Dortmunder Actien Brauerei / DAB
funky address for East African Breweries Ltd (Kenya Breweries)
funky address for Einbecker Brauhaus AG
funky address for Elgood and Sons Ltd
funky address for Erdinger WeissbrÃ¤u
funky address for Flensburger Brauerei GmbH Und Co. KG
funky address for Frederic Robinson Limited
funky address for Friesisches Brauhaus zu Jever GmbH & Co KG
funky address for Gasthaus & Gosebrauerei Bayerischer Bahnhof
funky address for Grolsch Bierbrouwerij N.V.
funky address for Grupo Modelo S.A. de C.V.
funky address for Gueuzerie Tilquin
funky address for Gulpener Bierbrouwerij B.V.
funky address for HaandBryggeriet
funky address for Hanssens Artisanaal bvba
funky address for Heineken Nederland B.V.
funky address for Henninger BrÃ¤u AG
funky address for Hofbrauhaus Wolters GmbH
funky address for HofbrÃ¤uhaus MÃ¼nchen
funky address for Industrial Cervecera S.A. / CompaÃ±Ã­a Cervecera De Nicaragua
funky address for Isle Of Skye Brewery
funky address for J.W. Lees & Co (Brewers) Ltd
funky address for Kaltenberg International / KÃ¶nig Ludwig International GmbH & Co.KG
funky address for KleinBrouwerij De Glazen Toren
funky address for Klosterbrauerei Andechs
funky address for Klosterbrauerei Ettal / Ettaler Klosterbetriebe GmbH
funky address for Klosterbrauerei Weissenohe / Klosterbrauerei WeiÃŸenohe Wirtshaus
funky address for Klosterbrauerei Weltenburg
funky address for Krombacher Brauerei
funky address for Kulmbacher Brauerei AG
funky address for KÃ¶nig-Brauerei GmbH
funky address for KÃ¶stritzer Schwarzbierbrauerei GmbH & Co.
funky address for Lammin Sahti Oy
funky address for Lao Brewery Co.
funky address for Les Brasseurs de Gayant
funky address for Licher Privatbrauerei
funky address for Little Creatures Brewing Company
funky address for Mahrs-BrÃ¤u
funky address for Melbourn Bros.
funky address for Microbrouwerij Achilles
funky address for Moorhouse's Brewery (Burnley) Ltd
funky address for NÃ¤rke Kulturbryggeri AB
funky address for NÃ¸gne Ã˜ - Det KompromisslÃ¸se Bryggeri A/S
funky address for NÃ¸rrebro Bryghus
funky address for OppigÃ¥rds Bryggeri AB
funky address for Oy Sinebrychoff Ab
funky address for Panil
funky address for Paulaner Brauerei GmbH & Co. KG
funky address for Perla Browary Lubelskie S.A.
funky address for Pivovar Klaster
funky address for Pivovar NÃ¡chod a.s.
funky address for Pivovar VelkÃ© Popovice a.s.
funky address for Pivovary Staropramen
funky address for Plzensky Prazdroj, a. s.
funky address for Privatbrauerei Frankenheim
funky address for Privatbrauerei Franz Inselkammer KG / Brauerei Aying
funky address for Privatbrauerei Gaffel Becker & Co.
funky address for Private Landbrauerei Scheuerer
funky address for Radeberger Exportbierbrauerei
funky address for Ringwood Brewery
funky address for Salopian Brewing Company Ltd
funky address for Samuel Smith Old Brewery (Tadcaster)
funky address for Scheldebrouwerij
funky address for Shepherd Neame Ltd
funky address for Sociedade Central de Cervejas
funky address for Spaten-Franziskaner-BrÃ¤u
funky address for St. GeorgenbrÃ¤u
funky address for St. Peter's Brewery Co Ltd
funky address for Stieglbrauerei zu Salzburg GmbH
funky address for Tennent Caledonian Breweries
funky address for The Caledonian Brewing Company

funky address for Thisted Bryghus
funky address for Uerige ObergÃ¤rige Hausbrauerei GmbH / Zum Uerige
funky address for Warsteiner Brauerei
funky address for Weissbierbrauerei Hopf
funky address for Williams Brothers Brewing Company
funky address for Wye Valley Brewery
funky address for WÃ¼rzburger HofbrÃ¤u AG
funky address for the Nils Oscar Company

,Brewery,brewery_id,review_overall,review_count,lat,lng,address,street_address,city,postal_code,country
0,(512) Brewing Company,17863.0,4.22,135,30.222972,-97.770152,"407 Radam Ln, Austin, TX 78745, United States",407 Radam Ln,Austin,TX 78745,United States
1,21st Amendment Brewery,735.0,3.71,2767,37.782525,-122.392460,"563 2nd St, San Francisco, CA 94107, United St...",563 2nd St,San Francisco,CA 94107,United States
2,AS Tartu Ã•lletehas,1349.0,2.76,58,58.385906,26.707300,"51007 Tartu, Estonia",,,51007 Tartu,Estonia
3,Abbaye de Leffe S.A.,470.0,3.74,1777,50.268889,4.907500,"Place de l'Abbaye 1, 5500 Dinant, Belgium",,Place de l'Abbaye 1,5500 Dinant,Belgium
4,Abita Brewing Co.,3.0,3.58,4922,30.482108,-90.055018,"21084 LA-36, Covington, LA 70433, United States",21084 LA-36,Covington,LA 70433,United States
6,Aktien-Brauerei Kaufbeuren AG,1623.0,3.89,55,47.878140,10.616120,"Hohe Buchleuthe 3, 87600 Kaufbeuren, Germany",,Hohe Buchleuthe 3,87600 Kaufbeuren,Germany
7,Alameda Brewhouse,2980.0,4.01,69,45.548459,-122.613639,"4765 NE Fremont St, Portland, OR 97213, United...",4765 NE Fremont St,Portland,OR 97213,United States
8,Alaskan Brewing Co.,429.0,3.85,3140,58.357573,-134.486348,"5364 Commercial Blvd, Juneau, AK 99801, United...",5364 Commercial Blvd,Juneau,AK 99801,United States
9,Aldaris,1382.0,3.40,194,57.005423,24.121007,"Tvaika iela 44, ZiemeÄ¼u rajons, RÄ«ga, LV-1005,...",ZiemeÄ¼u rajons,RÄ«ga,LV-1005,Latvia
10,Ale Asylum,13837.0,3.90,664,43.120465,-89.354151,"2002 Pankratz St, Madison, WI 53704, United St...",2002 Pankratz St,Madison,WI 53704,United States

<h1>A lot of indivual country input was cleaned one at a time</h1>

In [44]:
brewery_df["country"].unique()

array(['United States', 'Estonia', 'Belgium', 'Germany', 'Latvia',
       'Canada', 'Denmark', 'Singapore 639934', 'Poland', 'Barbados',
       'United Kingdom', 'Singapore', 'Netherlands', 'Italy', 'Thailand',
       'France', 'French Polynesia', 'Morocco', 'Austria', 'Aruba',
       'Trinidad & Tobago', 'Ireland', 'Sweden', 'Costa Rica',
       'Dominican Republic', 'Guatemala', 'Mexico', 'Colombia',
       'Sri Lanka', 'Puerto Rico', 'Australia', 'Kenya', 'Norway',
       'Spain', 'Nicaragua', 'Finland', 'Laos', 'South Korea', 'Czechia',
       'Lithuania', 'Vietnam', 'Philippines', 'Portugal'], dtype=object)

In [23]:
brewery_df.loc[(brewery_df["country"]=="Singapore 639934"),:]
brewery_df.loc[71,"country"]="Singapore"

In [24]:
brewery_df

,Brewery,brewery_id,review_overall,review_count,lat,lng,address,street_address,city,postal_code,country
0,(512) Brewing Company,17863.0,4.22,135,30.222972,-97.770152,"407 Radam Ln, Austin, TX 78745, United States",407 Radam Ln,Austin,TX 78745,United States
1,21st Amendment Brewery,735.0,3.71,2767,37.782525,-122.392460,"563 2nd St, San Francisco, CA 94107, United St...",563 2nd St,San Francisco,CA 94107,United States
2,AS Tartu Ã•lletehas,1349.0,2.76,58,58.385906,26.707300,"51007 Tartu, Estonia",,,51007 Tartu,Estonia
3,Abbaye de Leffe S.A.,470.0,3.74,1777,50.268889,4.907500,"Place de l'Abbaye 1, 5500 Dinant, Belgium",,Place de l'Abbaye 1,5500 Dinant,Belgium
4,Abita Brewing Co.,3.0,3.58,4922,30.482108,-90.055018,"21084 LA-36, Covington, LA 70433, United States",21084 LA-36,Covington,LA 70433,United States
...,...,...,...,...,...,...,...,...,...,...,...
867,Yellowstone Valley Brewing Co.,1125.0,3.61,64,45.780615,-108.508556,"3008 1st Ave N, Billings, MT 59101, United States",3008 1st Ave N,Billings,MT 59101,United States
869,Yuengling Brewery,23980.0,3.42,3342,40.683249,-76.197799,"420 Mahantongo St, Pottsville, PA 17901, Unite...",420 Mahantongo St,Pottsville,PA 17901,United States
870,Yukon Brewing Company,4701.0,3.87,54,60.738056,-135.078889,"102 Copper Rd, Whitehorse, YT Y1A 2Z6, Canada",102 Copper Rd,Whitehorse,YT Y1A 2Z6,Canada
874,the Nils Oscar Company,894.0,3.78,298,58.747829,17.006378,"FruÃ¤ngsgatan 2, 611 31 NykÃ¶ping, Sweden",,FruÃ¤ngsgatan 2,611 31 NykÃ¶ping,Sweden
876,Ã€ lâ€™abri de la TempÃªte,11256.0,3.89,55,47.351028,-61.947300,"286 Chemin Coulombe, L'Ã‰tang-du-Nord, QC G4T 3...",286 Chemin Coulombe,L'Ã‰tang-du-Nord,QC G4T 3V5,Canada

In [25]:
#realized I only cared about the country
stripped_brewery_df=brewery_df.drop(columns=["address" ,"street_address","city","postal_code"])
stripped_brewery_df

,Brewery,brewery_id,review_overall,review_count,lat,lng,country
0,(512) Brewing Company,17863.0,4.22,135,30.222972,-97.770152,United States
1,21st Amendment Brewery,735.0,3.71,2767,37.782525,-122.392460,United States
2,AS Tartu Ã•lletehas,1349.0,2.76,58,58.385906,26.707300,Estonia
3,Abbaye de Leffe S.A.,470.0,3.74,1777,50.268889,4.907500,Belgium
4,Abita Brewing Co.,3.0,3.58,4922,30.482108,-90.055018,United States
...,...,...,...,...,...,...,...
867,Yellowstone Valley Brewing Co.,1125.0,3.61,64,45.780615,-108.508556,United States
869,Yuengling Brewery,23980.0,3.42,3342,40.683249,-76.197799,United States
870,Yukon Brewing Company,4701.0,3.87,54,60.738056,-135.078889,Canada
874,the Nils Oscar Company,894.0,3.78,298,58.747829,17.006378,Sweden
876,Ã€ lâ€™abri de la TempÃªte,11256.0,3.89,55,47.351028,-61.947300,Canada

In [26]:
#beer_50review=beer_50review.reset_index()
beer_50review.head()

,index,beer_beerid,beer_name,brewery_name,beer_style,brewery_id,review_overall,review_aroma,review_appearance,review_taste,beer_abv,review_count
0,2,5,Amber,Abita Brewing Co.,Vienna Lager,3.0,3.549528,3.205189,3.485849,3.340802,4.5,424
1,3,6,Turbodog,Abita Brewing Co.,English Brown Ale,3.0,3.706956,3.515964,3.836374,3.645382,5.6,877
2,4,7,Purple Haze,Abita Brewing Co.,Fruit / Vegetable Beer,3.0,3.266313,3.179059,3.251138,3.101669,4.2,659
3,5,8,Wheat,Abita Brewing Co.,American Adjunct Lager,3.0,3.647059,3.080882,3.294118,3.235294,4.2,68
4,6,9,Golden,Abita Brewing Co.,American Pale Lager,3.0,3.400862,2.853448,3.051724,3.043103,4.2,116

In [36]:
#merge everything together
everything_df=pd.merge(stripped_brewery_df, beer_50review, on='brewery_id', how='outer')
everything_df.head()

,Brewery,brewery_id,review_overall_x,review_count_x,lat,lng,country,beer_beerid,beer_name,brewery_name,beer_style,review_overall_y,review_aroma,review_appearance,review_taste,review_palate,beer_abv,review_count_y
0,(512) Brewing Company,17863.0,4.22,135.0,30.222972,-97.770152,United States,43535,(512) IPA,(512) Brewing Company,American IPA,4.259259,4.129630,4.009259,4.185185,4.101852,7.0,54
1,(512) Brewing Company,17863.0,4.22,135.0,30.222972,-97.770152,United States,45617,(512) Pecan Porter,(512) Brewing Company,American Porter,4.185185,4.067901,4.166667,4.166667,3.981481,6.8,81
2,21st Amendment Brewery,735.0,3.71,2767.0,37.782525,-122.392460,United States,4202,Hell Or High Watermelon Wheat Beer,21st Amendment Brewery,Fruit / Vegetable Beer,3.388771,3.116525,3.237288,3.237288,3.325212,4.9,472
3,21st Amendment Brewery,735.0,3.71,2767.0,37.782525,-122.392460,United States,20781,21st Amendment IPA,21st Amendment Brewery,American IPA,3.890769,3.801538,3.977692,3.767692,3.771538,7.0,650
4,21st Amendment Brewery,735.0,3.71,2767.0,37.782525,-122.392460,United States,34791,Bitter American,21st Amendment Brewery,American Pale Ale (APA),4.118421,3.921053,3.927632,3.898026,3.769737,4.4,152

In [37]:
#drop nan values in everything
everything_df.dropna(inplace=True)
everything_df

,Brewery,brewery_id,review_overall_x,review_count_x,lat,lng,country,beer_beerid,beer_name,brewery_name,beer_style,review_overall_y,review_aroma,review_appearance,review_taste,review_palate,beer_abv,review_count_y
0,(512) Brewing Company,17863.0,4.22,135.0,30.222972,-97.770152,United States,43535,(512) IPA,(512) Brewing Company,American IPA,4.259259,4.129630,4.009259,4.185185,4.101852,7.0,54
1,(512) Brewing Company,17863.0,4.22,135.0,30.222972,-97.770152,United States,45617,(512) Pecan Porter,(512) Brewing Company,American Porter,4.185185,4.067901,4.166667,4.166667,3.981481,6.8,81
2,21st Amendment Brewery,735.0,3.71,2767.0,37.782525,-122.392460,United States,4202,Hell Or High Watermelon Wheat Beer,21st Amendment Brewery,Fruit / Vegetable Beer,3.388771,3.116525,3.237288,3.237288,3.325212,4.9,472
3,21st Amendment Brewery,735.0,3.71,2767.0,37.782525,-122.392460,United States,20781,21st Amendment IPA,21st Amendment Brewery,American IPA,3.890769,3.801538,3.977692,3.767692,3.771538,7.0,650
4,21st Amendment Brewery,735.0,3.71,2767.0,37.782525,-122.392460,United States,34791,Bitter American,21st Amendment Brewery,American Pale Ale (APA),4.118421,3.921053,3.927632,3.898026,3.769737,4.4,152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4397,the Nils Oscar Company,894.0,3.78,298.0,58.747829,17.006378,Sweden,3016,Nils Oscar Imperial Stout,the Nils Oscar Company,Russian Imperial Stout,3.911504,3.920354,3.818584,3.893805,3.654867,7.0,113
4398,the Nils Oscar Company,894.0,3.78,298.0,58.747829,17.006378,Sweden,6772,Nils Oscar Barley Wine,the Nils Oscar Company,English Barleywine,3.672131,3.598361,3.532787,3.688525,3.688525,9.5,61
4399,the Nils Oscar Company,894.0,3.78,298.0,58.747829,17.006378,Sweden,26047,Nils Oscar India Pale Ale,the Nils Oscar Company,English India Pale Ale (IPA),3.683099,3.450704,3.774648,3.626761,3.619718,5.3,71
4400,the Nils Oscar Company,894.0,3.78,298.0,58.747829,17.006378,Sweden,45574,Nils Oscar Coffee Stout,the Nils Oscar Company,American Stout,3.867925,3.867925,3.915094,3.915094,3.726415,6.0,53
4401,Ã€ lâ€™abri de la TempÃªte,11256.0,3.89,55.0,47.351028,-61.947300,Canada,29077,Corne De Brume,Ã€ lâ€™abri de la TempÃªte,Scotch Ale / Wee Heavy,3.890909,3.890909,3.918182,3.900000,3.818182,9.0,55

In [39]:
#drop redundent columns
everything_df=everything_df.drop(columns=["Brewery"])

In [40]:
#rearrange columns
everything_df=everything_df[["beer_name","brewery_name","beer_style","country","beer_abv","review_overall_y","review_aroma","review_appearance","review_palate"
              ,"review_taste","review_count_y","review_overall_x","review_count_x","lat","lng","beer_beerid","brewery_id"]]
everything_df

,beer_name,brewery_name,beer_style,country,beer_abv,review_overall_y,review_aroma,review_appearance,review_palate,review_taste,review_count_y,review_overall_x,review_count_x,lat,lng,beer_beerid,brewery_id
0,(512) IPA,(512) Brewing Company,American IPA,United States,7.0,4.259259,4.129630,4.009259,4.101852,4.185185,54,4.22,135.0,30.222972,-97.770152,43535,17863.0
1,(512) Pecan Porter,(512) Brewing Company,American Porter,United States,6.8,4.185185,4.067901,4.166667,3.981481,4.166667,81,4.22,135.0,30.222972,-97.770152,45617,17863.0
2,Hell Or High Watermelon Wheat Beer,21st Amendment Brewery,Fruit / Vegetable Beer,United States,4.9,3.388771,3.116525,3.237288,3.325212,3.237288,472,3.71,2767.0,37.782525,-122.392460,4202,735.0
3,21st Amendment IPA,21st Amendment Brewery,American IPA,United States,7.0,3.890769,3.801538,3.977692,3.771538,3.767692,650,3.71,2767.0,37.782525,-122.392460,20781,735.0
4,Bitter American,21st Amendment Brewery,American Pale Ale (APA),United States,4.4,4.118421,3.921053,3.927632,3.769737,3.898026,152,3.71,2767.0,37.782525,-122.392460,34791,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4397,Nils Oscar Imperial Stout,the Nils Oscar Company,Russian Imperial Stout,Sweden,7.0,3.911504,3.920354,3.818584,3.654867,3.893805,113,3.78,298.0,58.747829,17.006378,3016,894.0
4398,Nils Oscar Barley Wine,the Nils Oscar Company,English Barleywine,Sweden,9.5,3.672131,3.598361,3.532787,3.688525,3.688525,61,3.78,298.0,58.747829,17.006378,6772,894.0
4399,Nils Oscar India Pale Ale,the Nils Oscar Company,English India Pale Ale (IPA),Sweden,5.3,3.683099,3.450704,3.774648,3.619718,3.626761,71,3.78,298.0,58.747829,17.006378,26047,894.0
4400,Nils Oscar Coffee Stout,the Nils Oscar Company,American Stout,Sweden,6.0,3.867925,3.867925,3.915094,3.726415,3.915094,53,3.78,298.0,58.747829,17.006378,45574,894.0
4401,Corne De Brume,Ã€ lâ€™abri de la TempÃªte,Scotch Ale / Wee Heavy,Canada,9.0,3.890909,3.890909,3.918182,3.818182,3.900000,55,3.89,55.0,47.351028,-61.947300,29077,11256.0

In [41]:
#rename columns
everything_df=everything_df.rename(columns={"review_overall_y": "review_overall", "review_count_y": "beer_review_count",
                              "review_overall_x":"brewery_review","review_count_x":"brewery_review_count",
                             "beer_beerid":"beer_id"})
everything_df

,beer_name,brewery_name,beer_style,country,beer_abv,review_overall,review_aroma,review_appearance,review_palate,review_taste,beer_review_count,brewery_review,brewery_review_count,lat,lng,beer_id,brewery_id
0,(512) IPA,(512) Brewing Company,American IPA,United States,7.0,4.259259,4.129630,4.009259,4.101852,4.185185,54,4.22,135.0,30.222972,-97.770152,43535,17863.0
1,(512) Pecan Porter,(512) Brewing Company,American Porter,United States,6.8,4.185185,4.067901,4.166667,3.981481,4.166667,81,4.22,135.0,30.222972,-97.770152,45617,17863.0
2,Hell Or High Watermelon Wheat Beer,21st Amendment Brewery,Fruit / Vegetable Beer,United States,4.9,3.388771,3.116525,3.237288,3.325212,3.237288,472,3.71,2767.0,37.782525,-122.392460,4202,735.0
3,21st Amendment IPA,21st Amendment Brewery,American IPA,United States,7.0,3.890769,3.801538,3.977692,3.771538,3.767692,650,3.71,2767.0,37.782525,-122.392460,20781,735.0
4,Bitter American,21st Amendment Brewery,American Pale Ale (APA),United States,4.4,4.118421,3.921053,3.927632,3.769737,3.898026,152,3.71,2767.0,37.782525,-122.392460,34791,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4397,Nils Oscar Imperial Stout,the Nils Oscar Company,Russian Imperial Stout,Sweden,7.0,3.911504,3.920354,3.818584,3.654867,3.893805,113,3.78,298.0,58.747829,17.006378,3016,894.0
4398,Nils Oscar Barley Wine,the Nils Oscar Company,English Barleywine,Sweden,9.5,3.672131,3.598361,3.532787,3.688525,3.688525,61,3.78,298.0,58.747829,17.006378,6772,894.0
4399,Nils Oscar India Pale Ale,the Nils Oscar Company,English India Pale Ale (IPA),Sweden,5.3,3.683099,3.450704,3.774648,3.619718,3.626761,71,3.78,298.0,58.747829,17.006378,26047,894.0
4400,Nils Oscar Coffee Stout,the Nils Oscar Company,American Stout,Sweden,6.0,3.867925,3.867925,3.915094,3.726415,3.915094,53,3.78,298.0,58.747829,17.006378,45574,894.0
4401,Corne De Brume,Ã€ lâ€™abri de la TempÃªte,Scotch Ale / Wee Heavy,Canada,9.0,3.890909,3.890909,3.918182,3.818182,3.900000,55,3.89,55.0,47.351028,-61.947300,29077,11256.0

In [43]:
#export to csv
everything_df.to_csv('Output/clean_beer_data_try2.csv')